// <auto-generated />
using System;
using EnglishExamApp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnglishExamApp.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.AiFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AiComment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("aiComment");

                    b.Property<Guid>("AnswerId")
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("answerId");

                    b.Property<double>("BandScore")
                        .HasColumnType("float")
                        .HasColumnName("bandScore");

                    b.Property<double?>("ConfidenceScore")
                        .HasColumnType("float")
                        .HasColumnName("confidenceScore");

                    b.Property<string>("EvidenceData")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("evidenceData");

                    b.Property<string>("Improvements")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("improvements");

                    b.Property<Guid>("RubricId")
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("rubricId");

                    b.HasKey("Id");

                    b.HasIndex("AnswerId");

                    b.HasIndex("RubricId");

                    b.ToTable("ai_feedbacks", (string)null);
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.DocumentUpload", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("errorMessage");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("fileName");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("fileUrl");

                    b.Property<Guid?>("GeneratedExamId")
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("generatedExamId");

                    b.Property<string>("ProcessStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("processStatus");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedAt")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid>("UploadedBy")
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("uploadedBy");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedExamId");

                    b.HasIndex("UploadedBy");

                    b.ToTable("document_uploads", (string)null);
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.Exam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid?>("CreatedBy")
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("createdBy");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int")
                        .HasColumnName("durationMinutes");

                    b.Property<string>("ExamType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("examType");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("isPublished");

                    b.Property<string>("SourcePdfUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("sourcePdfUrl");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<double?>("TotalPoints")
                        .HasColumnType("float")
                        .HasColumnName("totalPoints");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("exams", (string)null);
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.ExamSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("ExamId")
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("examId");

                    b.Property<int?>("OrderIndex")
                        .HasColumnType("int")
                        .HasColumnName("orderIndex");

                    b.Property<string>("SkillType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("skillType");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.ToTable("exam_sections", (string)null);
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.ExamSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("endedAt");

                    b.Property<Guid>("ExamId")
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("examId");

                    b.Property<string>("HighlightsData")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("highlightsData");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("startedAt")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<int?>("TimeRemaining")
                        .HasColumnType("int")
                        .HasColumnName("timeRemaining");

                    b.Property<Guid>("UserId")
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.HasIndex("UserId");

                    b.ToTable("exam_sessions", (string)null);
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.ExamTag", b =>
                {
                    b.Property<Guid>("ExamId")
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("examId");

                    b.Property<Guid>("TagId")
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tagId");

                    b.HasKey("ExamId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("exam_tags", (string)null);
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.ListeningPart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AudioUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("audioUrl");

                    b.Property<string>("ContextDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contextDescription");

                    b.Property<int?>("PartNumber")
                        .HasColumnType("int")
                        .HasColumnName("partNumber");

                    b.Property<Guid>("SectionId")
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sectionId");

                    b.Property<string>("TranscriptData")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("transcriptData");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.ToTable("listening_parts", (string)null);
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("isRead");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("paymentMethod");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("transactionId");

                    b.Property<Guid>("UserId")
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.PhonemeAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ActualPhoneme")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("actualPhoneme");

                    b.Property<string>("ExpectedPhoneme")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("expectedPhoneme");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("bit")
                        .HasColumnName("isCorrect");

                    b.Property<Guid>("TranscriptId")
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("transcriptId");

                    b.Property<string>("Word")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("word");

                    b.HasKey("Id");

                    b.HasIndex("TranscriptId");

                    b.ToTable("phoneme_analyses", (string)null);
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<string>("CorrectAnswer")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("correctAnswer");

                    b.Property<string>("EvidenceLocation")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("evidenceLocation");

                    b.Property<string>("Explanation")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("explanation");

                    b.Property<Guid>("GroupId")
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("groupId");

                    b.Property<double>("Points")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(1.0)
                        .HasColumnName("points");

                    b.Property<string>("Provenance")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("provenance");

                    b.Property<int?>("QuestionNumber")
                        .HasColumnType("int")
                        .HasColumnName("questionNumber");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("questions", (string)null);
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.QuestionGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AssetsData")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("assetsData");

                    b.Property<string>("ContentData")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contentData");

                    b.Property<int?>("EndQuestion")
                        .HasColumnType("int")
                        .HasColumnName("endQuestion");

                    b.Property<string>("GroupType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("groupType");

                    b.Property<string>("Instruction")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("instruction");

                    b.Property<Guid?>("ListeningPartId")
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("listeningPartId");

                    b.Property<Guid?>("PassageId")
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("passageId");

                    b.Property<int?>("StartQuestion")
                        .HasColumnType("int")
                        .HasColumnName("startQuestion");

                    b.HasKey("Id");

                    b.HasIndex("ListeningPartId");

                    b.HasIndex("PassageId");

                    b.ToTable("question_groups", (string)null);
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.QuestionOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("imageUrl");

                    b.Property<bool>("IsCorrect")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("isCorrect");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("optionText");

                    b.Property<int?>("OrderIndex")
                        .HasColumnType("int")
                        .HasColumnName("orderIndex");

                    b.Property<Guid>("QuestionId")
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("questionId");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("question_options", (string)null);
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.ReadingPassage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AssetsData")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("assetsData");

                    b.Property<string>("ParagraphsData")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("paragraphsData");

                    b.Property<int?>("PassageNumber")
                        .HasColumnType("int")
                        .HasColumnName("passageNumber");

                    b.Property<Guid>("SectionId")
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sectionId");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.ToTable("reading_passages", (string)null);
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.SavedQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<Guid>("QuestionId")
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("questionId");

                    b.Property<DateTime>("SavedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("savedAt")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid>("UserId")
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId");

                    b.ToTable("saved_questions", (string)null);
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.ScoringResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<double?>("ListeningScore")
                        .HasColumnType("float")
                        .HasColumnName("listeningScore");

                    b.Property<string>("OverallFeedback")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("overallFeedback");

                    b.Property<double?>("ReadingScore")
                        .HasColumnType("float")
                        .HasColumnName("readingScore");

                    b.Property<DateTime>("ScoredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("scoredAt")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid>("SessionId")
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sessionId");

                    b.Property<double?>("SpeakingScore")
                        .HasColumnType("float")
                        .HasColumnName("speakingScore");

                    b.Property<double?>("TotalBandScore")
                        .HasColumnType("float")
                        .HasColumnName("totalBandScore");

                    b.Property<double?>("WritingScore")
                        .HasColumnType("float")
                        .HasColumnName("writingScore");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("scoring_results", (string)null);
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.ScoringRubric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("CriteriaName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("criteriaName");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<double?>("MaxBand")
                        .HasColumnType("float")
                        .HasColumnName("maxBand");

                    b.Property<string>("SkillType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("skillType");

                    b.HasKey("Id");

                    b.ToTable("scoring_rubrics", (string)null);
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.SpeakingPart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int?>("PartNumber")
                        .HasColumnType("int")
                        .HasColumnName("partNumber");

                    b.Property<Guid>("SectionId")
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sectionId");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.ToTable("speaking_parts", (string)null);
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.SpeakingQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AudioPromptUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("audioPromptUrl");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<string>("CueCardPoints")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cueCardPoints");

                    b.Property<int?>("OrderIndex")
                        .HasColumnType("int")
                        .HasColumnName("orderIndex");

                    b.Property<Guid>("PartId")
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("partId");

                    b.HasKey("Id");

                    b.HasIndex("PartId");

                    b.ToTable("speaking_questions", (string)null);
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.SpeechTranscript", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("AudioRecordId")
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("audioRecordId");

                    b.Property<double?>("ConfidenceScore")
                        .HasColumnType("float")
                        .HasColumnName("confidenceScore");

                    b.Property<string>("PauseStatsData")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pauseStatsData");

                    b.Property<string>("TranscriptText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("transcriptText");

                    b.Property<double?>("WordErrorRate")
                        .HasColumnType("float")
                        .HasColumnName("wordErrorRate");

                    b.Property<string>("WordTimestampsData")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("wordTimestampsData");

                    b.HasKey("Id");

                    b.HasIndex("AudioRecordId");

                    b.ToTable("speech_transcripts", (string)null);
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int")
                        .HasColumnName("durationDays");

                    b.Property<string>("Features")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("features");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("isActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ActivationToken")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ActivationToken");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("avatarUrl");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DailyStreakCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("dailyStreakCount");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Department");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("displayName");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<int>("ExperiencePoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("experiencePoints");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("isActive");

                    b.Property<bool>("IsEmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsEmailConfirmed");

                    b.Property<bool>("IsOnline")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsOnline");

                    b.Property<DateTime?>("LastActivityAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("lastActivityAt");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastLoginAt");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastSeenAt");

                    b.Property<int>("LongestStreakCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("longestStreakCount");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Notes");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("passwordHash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Phone");

                    b.Property<string>("Position")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Position");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("local")
                        .HasColumnName("Provider");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("RefreshToken");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime2")
                        .HasColumnName("RefreshTokenExpiry");

                    b.Property<string>("ResetPasswordToken")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ResetPasswordToken");

                    b.Property<DateTime?>("TokenExpiry")
                        .HasColumnType("datetime2")
                        .HasColumnName("TokenExpiry");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedAt")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.UserAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AnswerText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("answerText");

                    b.Property<Guid?>("QuestionId")
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("questionId");

                    b.Property<double>("ScoreEarned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0)
                        .HasColumnName("scoreEarned");

                    b.Property<Guid>("SessionId")
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sessionId");

                    b.Property<Guid?>("SpeakingQuestionId")
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("speakingQuestionId");

                    b.Property<DateTime>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("submittedAt")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid?>("WritingTaskId")
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("writingTaskId");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SessionId");

                    b.HasIndex("SpeakingQuestionId");

                    b.HasIndex("WritingTaskId");

                    b.ToTable("user_answers", (string)null);
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.UserAudioRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("AnswerId")
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("answerId");

                    b.Property<string>("AudioQualityData")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("audioQualityData");

                    b.Property<string>("AudioUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("audioUrl");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("float")
                        .HasColumnName("durationSeconds");

                    b.Property<int?>("FileSizeKB")
                        .HasColumnType("int")
                        .HasColumnName("fileSizeKB");

                    b.Property<double?>("SpeechRatio")
                        .HasColumnType("float")
                        .HasColumnName("speechRatio");

                    b.HasKey("Id");

                    b.HasIndex("AnswerId");

                    b.ToTable("user_audio_records", (string)null);
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("userId");

                    b.Property<Guid>("RoleId")
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("roleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.UserSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("endDate");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("startDate");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("SubscriptionId")
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("subscriptionId");

                    b.Property<Guid>("UserId")
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("UserId");

                    b.ToTable("user_subscriptions", (string)null);
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.WritingTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AssetsData")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("assetsData");

                    b.Property<int>("MinWords")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(150)
                        .HasColumnName("minWords");

                    b.Property<string>("PromptText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("promptText");

                    b.Property<Guid>("SectionId")
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sectionId");

                    b.Property<int?>("TaskNumber")
                        .HasColumnType("int")
                        .HasColumnName("taskNumber");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.ToTable("writing_tasks", (string)null);
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.AiFeedback", b =>
                {
                    b.HasOne("EnglishExamApp.Domain.Entities.UserAnswer", "Answer")
                        .WithMany("AiFeedbacks")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnglishExamApp.Domain.Entities.ScoringRubric", "Rubric")
                        .WithMany("AiFeedbacks")
                        .HasForeignKey("RubricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("Rubric");
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.DocumentUpload", b =>
                {
                    b.HasOne("EnglishExamApp.Domain.Entities.Exam", "GeneratedExam")
                        .WithMany("DocumentUploads")
                        .HasForeignKey("GeneratedExamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EnglishExamApp.Domain.Entities.User", "Uploader")
                        .WithMany("DocumentUploads")
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GeneratedExam");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.Exam", b =>
                {
                    b.HasOne("EnglishExamApp.Domain.Entities.User", "Creator")
                        .WithMany("CreatedExams")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.ExamSection", b =>
                {
                    b.HasOne("EnglishExamApp.Domain.Entities.Exam", "Exam")
                        .WithMany("ExamSections")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.ExamSession", b =>
                {
                    b.HasOne("EnglishExamApp.Domain.Entities.Exam", "Exam")
                        .WithMany("ExamSessions")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnglishExamApp.Domain.Entities.User", "User")
                        .WithMany("ExamSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.ExamTag", b =>
                {
                    b.HasOne("EnglishExamApp.Domain.Entities.Exam", "Exam")
                        .WithMany("ExamTags")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnglishExamApp.Domain.Entities.Tag", "Tag")
                        .WithMany("ExamTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.ListeningPart", b =>
                {
                    b.HasOne("EnglishExamApp.Domain.Entities.ExamSection", "Section")
                        .WithMany("ListeningParts")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.Notification", b =>
                {
                    b.HasOne("EnglishExamApp.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.Payment", b =>
                {
                    b.HasOne("EnglishExamApp.Domain.Entities.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.PhonemeAnalysis", b =>
                {
                    b.HasOne("EnglishExamApp.Domain.Entities.SpeechTranscript", "Transcript")
                        .WithMany("PhonemeAnalyses")
                        .HasForeignKey("TranscriptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transcript");
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.Question", b =>
                {
                    b.HasOne("EnglishExamApp.Domain.Entities.QuestionGroup", "Group")
                        .WithMany("Questions")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.QuestionGroup", b =>
                {
                    b.HasOne("EnglishExamApp.Domain.Entities.ListeningPart", "ListeningPart")
                        .WithMany("QuestionGroups")
                        .HasForeignKey("ListeningPartId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("EnglishExamApp.Domain.Entities.ReadingPassage", "Passage")
                        .WithMany("QuestionGroups")
                        .HasForeignKey("PassageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ListeningPart");

                    b.Navigation("Passage");
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.QuestionOption", b =>
                {
                    b.HasOne("EnglishExamApp.Domain.Entities.Question", "Question")
                        .WithMany("QuestionOptions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.ReadingPassage", b =>
                {
                    b.HasOne("EnglishExamApp.Domain.Entities.ExamSection", "Section")
                        .WithMany("ReadingPassages")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.SavedQuestion", b =>
                {
                    b.HasOne("EnglishExamApp.Domain.Entities.Question", "Question")
                        .WithMany("SavedQuestions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnglishExamApp.Domain.Entities.User", "User")
                        .WithMany("SavedQuestions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.ScoringResult", b =>
                {
                    b.HasOne("EnglishExamApp.Domain.Entities.ExamSession", "Session")
                        .WithMany("ScoringResults")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.SpeakingPart", b =>
                {
                    b.HasOne("EnglishExamApp.Domain.Entities.ExamSection", "Section")
                        .WithMany("SpeakingParts")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.SpeakingQuestion", b =>
                {
                    b.HasOne("EnglishExamApp.Domain.Entities.SpeakingPart", "Part")
                        .WithMany("SpeakingQuestions")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.SpeechTranscript", b =>
                {
                    b.HasOne("EnglishExamApp.Domain.Entities.UserAudioRecord", "AudioRecord")
                        .WithMany("SpeechTranscripts")
                        .HasForeignKey("AudioRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AudioRecord");
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.UserAnswer", b =>
                {
                    b.HasOne("EnglishExamApp.Domain.Entities.Question", "Question")
                        .WithMany("UserAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("EnglishExamApp.Domain.Entities.ExamSession", "Session")
                        .WithMany("UserAnswers")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnglishExamApp.Domain.Entities.SpeakingQuestion", "SpeakingQuestion")
                        .WithMany("UserAnswers")
                        .HasForeignKey("SpeakingQuestionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("EnglishExamApp.Domain.Entities.WritingTask", "WritingTask")
                        .WithMany("UserAnswers")
                        .HasForeignKey("WritingTaskId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Question");

                    b.Navigation("Session");

                    b.Navigation("SpeakingQuestion");

                    b.Navigation("WritingTask");
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.UserAudioRecord", b =>
                {
                    b.HasOne("EnglishExamApp.Domain.Entities.UserAnswer", "Answer")
                        .WithMany("UserAudioRecords")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Answer");
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("EnglishExamApp.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnglishExamApp.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.UserSubscription", b =>
                {
                    b.HasOne("EnglishExamApp.Domain.Entities.Subscription", "Subscription")
                        .WithMany("UserSubscriptions")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnglishExamApp.Domain.Entities.User", "User")
                        .WithMany("UserSubscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.WritingTask", b =>
                {
                    b.HasOne("EnglishExamApp.Domain.Entities.ExamSection", "Section")
                        .WithMany("WritingTasks")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.Exam", b =>
                {
                    b.Navigation("DocumentUploads");

                    b.Navigation("ExamSections");

                    b.Navigation("ExamSessions");

                    b.Navigation("ExamTags");
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.ExamSection", b =>
                {
                    b.Navigation("ListeningParts");

                    b.Navigation("ReadingPassages");

                    b.Navigation("SpeakingParts");

                    b.Navigation("WritingTasks");
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.ExamSession", b =>
                {
                    b.Navigation("ScoringResults");

                    b.Navigation("UserAnswers");
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.ListeningPart", b =>
                {
                    b.Navigation("QuestionGroups");
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.Question", b =>
                {
                    b.Navigation("QuestionOptions");

                    b.Navigation("SavedQuestions");

                    b.Navigation("UserAnswers");
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.QuestionGroup", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.ReadingPassage", b =>
                {
                    b.Navigation("QuestionGroups");
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.ScoringRubric", b =>
                {
                    b.Navigation("AiFeedbacks");
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.SpeakingPart", b =>
                {
                    b.Navigation("SpeakingQuestions");
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.SpeakingQuestion", b =>
                {
                    b.Navigation("UserAnswers");
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.SpeechTranscript", b =>
                {
                    b.Navigation("PhonemeAnalyses");
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.Subscription", b =>
                {
                    b.Navigation("UserSubscriptions");
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.Tag", b =>
                {
                    b.Navigation("ExamTags");
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.User", b =>
                {
                    b.Navigation("CreatedExams");

                    b.Navigation("DocumentUploads");

                    b.Navigation("ExamSessions");

                    b.Navigation("Notifications");

                    b.Navigation("Payments");

                    b.Navigation("SavedQuestions");

                    b.Navigation("UserRoles");

                    b.Navigation("UserSubscriptions");
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.UserAnswer", b =>
                {
                    b.Navigation("AiFeedbacks");

                    b.Navigation("UserAudioRecords");
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.UserAudioRecord", b =>
                {
                    b.Navigation("SpeechTranscripts");
                });

            modelBuilder.Entity("EnglishExamApp.Domain.Entities.WritingTask", b =>
                {
                    b.Navigation("UserAnswers");
                });
#pragma warning restore 612, 618
        }
    }
}
