// <auto-generated />
using System;
using EnglishLearningApp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnglishLearningApp.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260225083854_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EnglishLearningApp.Domain.Entities.Course", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(36)")
                        .HasColumnName("createdBy");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("DifficultyLevel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("difficultyLevel");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("isPublished");

                    b.Property<string>("SkillType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("skillType");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("thumbnailUrl");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedAt")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("courses", (string)null);
                });

            modelBuilder.Entity("EnglishLearningApp.Domain.Entities.Exam", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(36)")
                        .HasColumnName("id");

                    b.Property<string>("CourseId")
                        .HasColumnType("NVARCHAR(36)")
                        .HasColumnName("courseId");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int?>("Duration")
                        .HasColumnType("int")
                        .HasColumnName("duration");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("isPublished");

                    b.Property<double?>("PassingScore")
                        .HasColumnType("float")
                        .HasColumnName("passingScore");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<int?>("TotalPoints")
                        .HasColumnType("int")
                        .HasColumnName("totalPoints");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("exams", (string)null);
                });

            modelBuilder.Entity("EnglishLearningApp.Domain.Entities.ExamQuestion", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(36)")
                        .HasColumnName("id");

                    b.Property<string>("ExamId")
                        .HasColumnType("NVARCHAR(36)")
                        .HasColumnName("examId");

                    b.Property<int?>("OrderIndex")
                        .HasColumnType("int")
                        .HasColumnName("orderIndex");

                    b.Property<string>("QuestionId")
                        .HasColumnType("NVARCHAR(36)")
                        .HasColumnName("questionId");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.HasIndex("QuestionId");

                    b.ToTable("exam_questions", (string)null);
                });

            modelBuilder.Entity("EnglishLearningApp.Domain.Entities.ExamSession", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("DraftData")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("draftData");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("endedAt");

                    b.Property<string>("ExamId")
                        .HasColumnType("NVARCHAR(36)")
                        .HasColumnName("examId");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("startedAt")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<int?>("TimeRemaining")
                        .HasColumnType("int")
                        .HasColumnName("timeRemaining");

                    b.Property<string>("UserId")
                        .HasColumnType("NVARCHAR(36)")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.HasIndex("UserId");

                    b.ToTable("exam_sessions", (string)null);
                });

            modelBuilder.Entity("EnglishLearningApp.Domain.Entities.LearningProgress", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(36)")
                        .HasColumnName("id");

                    b.Property<int>("CompletedLessons")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("completedLessons");

                    b.Property<string>("CourseId")
                        .HasColumnType("NVARCHAR(36)")
                        .HasColumnName("courseId");

                    b.Property<DateTime>("LastAccessedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("lastAccessedAt")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("UserId")
                        .HasColumnType("NVARCHAR(36)")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId");

                    b.ToTable("learning_progress", (string)null);
                });

            modelBuilder.Entity("EnglishLearningApp.Domain.Entities.Lesson", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(36)")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<string>("CourseId")
                        .HasColumnType("NVARCHAR(36)")
                        .HasColumnName("courseId");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("Duration")
                        .HasColumnType("int")
                        .HasColumnName("duration");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("isPublished");

                    b.Property<int?>("OrderIndex")
                        .HasColumnType("int")
                        .HasColumnName("orderIndex");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("thumbnailUrl");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("lessons", (string)null);
                });

            modelBuilder.Entity("EnglishLearningApp.Domain.Entities.Notification", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("isRead");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<string>("UserId")
                        .HasColumnType("NVARCHAR(36)")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("EnglishLearningApp.Domain.Entities.Question", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(36)")
                        .HasColumnName("id");

                    b.Property<string>("AudioUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("audioUrl");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<string>("CorrectAnswer")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("correctAnswer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("imageUrl");

                    b.Property<string>("LessonId")
                        .HasColumnType("NVARCHAR(36)")
                        .HasColumnName("lessonId");

                    b.Property<string>("Options")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("options");

                    b.Property<int?>("OrderIndex")
                        .HasColumnType("int")
                        .HasColumnName("orderIndex");

                    b.Property<int>("Points")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("points");

                    b.Property<string>("QuestionType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("questionType");

                    b.Property<string>("SkillType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("skillType");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("questions", (string)null);
                });

            modelBuilder.Entity("EnglishLearningApp.Domain.Entities.ScoringResult", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(36)")
                        .HasColumnName("id");

                    b.Property<double?>("BandScore")
                        .HasColumnType("float")
                        .HasColumnName("bandScore");

                    b.Property<double?>("CoherenceScore")
                        .HasColumnType("float")
                        .HasColumnName("coherenceScore");

                    b.Property<string>("Feedback")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("feedback");

                    b.Property<double?>("FluencyScore")
                        .HasColumnType("float")
                        .HasColumnName("fluencyScore");

                    b.Property<double?>("GrammarScore")
                        .HasColumnType("float")
                        .HasColumnName("grammarScore");

                    b.Property<double?>("PronunciationScore")
                        .HasColumnType("float")
                        .HasColumnName("pronunciationScore");

                    b.Property<DateTime>("ScoredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("scoredAt")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("SessionId")
                        .HasColumnType("NVARCHAR(36)")
                        .HasColumnName("sessionId");

                    b.Property<double?>("TotalScore")
                        .HasColumnType("float")
                        .HasColumnName("totalScore");

                    b.Property<string>("Transcript")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("transcript");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique()
                        .HasFilter("[sessionId] IS NOT NULL");

                    b.ToTable("scoring_results", (string)null);
                });

            modelBuilder.Entity("EnglishLearningApp.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(36)")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("avatarUrl");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("displayName");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("isActive");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("passwordHash");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedAt")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("EnglishLearningApp.Domain.Entities.UserAnswer", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(36)")
                        .HasColumnName("id");

                    b.Property<string>("AnswerText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("answerText");

                    b.Property<string>("AudioUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("audioUrl");

                    b.Property<bool>("IsAutoSaved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("isAutoSaved");

                    b.Property<string>("QuestionId")
                        .HasColumnType("NVARCHAR(36)")
                        .HasColumnName("questionId");

                    b.Property<string>("SessionId")
                        .HasColumnType("NVARCHAR(36)")
                        .HasColumnName("sessionId");

                    b.Property<DateTime>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("submittedAt")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SessionId");

                    b.ToTable("user_answers", (string)null);
                });

            modelBuilder.Entity("EnglishLearningApp.Domain.Entities.Course", b =>
                {
                    b.HasOne("EnglishLearningApp.Domain.Entities.User", "Creator")
                        .WithMany("CreatedCourses")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("EnglishLearningApp.Domain.Entities.Exam", b =>
                {
                    b.HasOne("EnglishLearningApp.Domain.Entities.Course", "Course")
                        .WithMany("Exams")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Course");
                });

            modelBuilder.Entity("EnglishLearningApp.Domain.Entities.ExamQuestion", b =>
                {
                    b.HasOne("EnglishLearningApp.Domain.Entities.Exam", "Exam")
                        .WithMany("ExamQuestions")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EnglishLearningApp.Domain.Entities.Question", "Question")
                        .WithMany("ExamQuestions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Exam");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("EnglishLearningApp.Domain.Entities.ExamSession", b =>
                {
                    b.HasOne("EnglishLearningApp.Domain.Entities.Exam", "Exam")
                        .WithMany("ExamSessions")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EnglishLearningApp.Domain.Entities.User", "User")
                        .WithMany("ExamSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Exam");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnglishLearningApp.Domain.Entities.LearningProgress", b =>
                {
                    b.HasOne("EnglishLearningApp.Domain.Entities.Course", "Course")
                        .WithMany("LearningProgresses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EnglishLearningApp.Domain.Entities.User", "User")
                        .WithMany("LearningProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnglishLearningApp.Domain.Entities.Lesson", b =>
                {
                    b.HasOne("EnglishLearningApp.Domain.Entities.Course", "Course")
                        .WithMany("Lessons")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Course");
                });

            modelBuilder.Entity("EnglishLearningApp.Domain.Entities.Notification", b =>
                {
                    b.HasOne("EnglishLearningApp.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnglishLearningApp.Domain.Entities.Question", b =>
                {
                    b.HasOne("EnglishLearningApp.Domain.Entities.Lesson", "Lesson")
                        .WithMany("Questions")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("EnglishLearningApp.Domain.Entities.ScoringResult", b =>
                {
                    b.HasOne("EnglishLearningApp.Domain.Entities.ExamSession", "Session")
                        .WithOne("ScoringResult")
                        .HasForeignKey("EnglishLearningApp.Domain.Entities.ScoringResult", "SessionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Session");
                });

            modelBuilder.Entity("EnglishLearningApp.Domain.Entities.UserAnswer", b =>
                {
                    b.HasOne("EnglishLearningApp.Domain.Entities.Question", "Question")
                        .WithMany("UserAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EnglishLearningApp.Domain.Entities.ExamSession", "Session")
                        .WithMany("UserAnswers")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Question");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("EnglishLearningApp.Domain.Entities.Course", b =>
                {
                    b.Navigation("Exams");

                    b.Navigation("LearningProgresses");

                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("EnglishLearningApp.Domain.Entities.Exam", b =>
                {
                    b.Navigation("ExamQuestions");

                    b.Navigation("ExamSessions");
                });

            modelBuilder.Entity("EnglishLearningApp.Domain.Entities.ExamSession", b =>
                {
                    b.Navigation("ScoringResult");

                    b.Navigation("UserAnswers");
                });

            modelBuilder.Entity("EnglishLearningApp.Domain.Entities.Lesson", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("EnglishLearningApp.Domain.Entities.Question", b =>
                {
                    b.Navigation("ExamQuestions");

                    b.Navigation("UserAnswers");
                });

            modelBuilder.Entity("EnglishLearningApp.Domain.Entities.User", b =>
                {
                    b.Navigation("CreatedCourses");

                    b.Navigation("ExamSessions");

                    b.Navigation("LearningProgresses");

                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
