name: Deploy Backend to Hugging Face

on:
  push:
    branches:
      - main
    paths:
      - 'english4u-backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git subtree push --prefix english4u-backend https://minhtri1:$HF_TOKEN@huggingface.co/spaces/minhtri1/english4u-backend main